# ML-04 — Search Intelligence Data Contract

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Rupam072006/flyrank-ml-internship/blob/main/work/notebooks/w03_data_contract.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

In [36]:
!pip install -q duckdb datasets huggingface_hub pyarrow pandas

In [37]:
import duckdb
import pandas as pd
from datasets import load_dataset

In [38]:
import duckdb

con = duckdb.connect()

In [39]:
con.execute("""
CREATE SECRET(
TYPE huggingface,
TOKEN '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'
)
""")

In [40]:
warehouse = "hf://datasets/FlyRank/internship-warehouse"

In [41]:
con.sql(f"""
SELECT COUNT(*)
FROM read_parquet(
'{warehouse}/fact_content_daily_performance/**/*.parquet'
)
""")

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│     78835655 │
└──────────────┘

In [42]:
con.sql(f"""
DESCRIBE
SELECT *
FROM read_parquet(
'{warehouse}/fact_content_daily_performance/**/*.parquet'
)
""").df()

                 column_name column_type null   key default extra
0                report_date        DATE  YES  None    None  None
1             client_hash_id     VARCHAR  YES  None    None  None
2            content_hash_id     VARCHAR  YES  None    None  None
3             client_has_gsc     BOOLEAN  YES  None    None  None
4             client_has_ga4     BOOLEAN  YES  None    None  None
5         gsc_data_available     BOOLEAN  YES  None    None  None
6         ga4_data_available     BOOLEAN  YES  None    None  None
7            gsc_impressions      BIGINT  YES  None    None  None
8                 gsc_clicks      BIGINT  YES  None    None  None
9           gsc_sum_position      BIGINT  YES  None    None  None
10          gsc_avg_position      DOUBLE  YES  None    None  None
11             ga4_pageviews      BIGINT  YES  None    None  None
12              ga4_sessions      BIGINT  YES  None    None  None
13                 ga4_users      BIGINT  YES  None    None  None
14      ga4_engaged_sessions      BIGINT  YES  None    None  None
15  ga4_total_engagement_sec      BIGINT  YES  None    None  None
16          sessions_organic      BIGINT  YES  None    None  None
17           sessions_direct      BIGINT  YES  None    None  None
18         sessions_referral      BIGINT  YES  None    None  None
19           sessions_social      BIGINT  YES  None    None  None
20             sessions_paid      BIGINT  YES  None    None  None
21               sessions_ai      BIGINT  YES  None    None  None
22                ai_chatgpt      BIGINT  YES  None    None  None
23             ai_perplexity      BIGINT  YES  None    None  None
24                 ai_gemini      BIGINT  YES  None    None  None
25                ai_copilot      BIGINT  YES  None    None  None
26                 ai_claude      BIGINT  YES  None    None  None
27                   ai_meta      BIGINT  YES  None    None  None
28                  ai_other      BIGINT  YES  None    None  None
29             scroll_events      BIGINT  YES  None    None  None
30                     month     VARCHAR  YES  None    None  None

In [43]:
con.sql(f"""
SELECT *
FROM read_parquet(
'{warehouse}/fact_content_daily_performance/**/*.parquet'
)
LIMIT 10
""").df()

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events,month
0,2025-01-27,client_9958f0a7ae1df715,content_3b70a18ea133b2bb,True,True,True,False,30,0,115,...,0,0,0,0,0,0,0,0,0,2025-01
1,2025-01-27,client_9958f0a7ae1df715,content_fe8e8155ce1d47a2,True,True,True,False,5,0,358,...,0,0,0,0,0,0,0,0,0,2025-01
2,2025-01-27,client_9958f0a7ae1df715,content_b4462a1b90640058,True,True,True,False,1,0,34,...,0,0,0,0,0,0,0,0,0,2025-01
3,2025-01-27,client_9958f0a7ae1df715,content_c899aef92518c714,True,True,True,False,6,0,140,...,0,0,0,0,0,0,0,0,0,2025-01
4,2025-01-27,client_9958f0a7ae1df715,content_c7c1d2e68d9d0964,True,True,True,False,5,0,89,...,0,0,0,0,0,0,0,0,0,2025-01
5,2025-01-27,client_9958f0a7ae1df715,content_c782fa8abd4fce5e,True,True,True,False,21,0,1050,...,0,0,0,0,0,0,0,0,0,2025-01
6,2025-01-27,client_9958f0a7ae1df715,content_ae5e5fd6edff550f,True,True,True,False,13,0,127,...,0,0,0,0,0,0,0,0,0,2025-01
7,2025-01-27,client_9958f0a7ae1df715,content_a64143f6e4a21ffe,True,True,True,False,29,0,356,...,0,0,0,0,0,0,0,0,0,2025-01
8,2025-01-27,client_9958f0a7ae1df715,content_e281674658070602,True,True,True,False,5,0,103,...,0,0,0,0,0,0,0,0,0,2025-01
9,2025-01-27,client_9958f0a7ae1df715,content_658f53fa439c66ca,True,True,True,False,8,0,304,...,0,0,0,0,0,0,0,0,0,2025-01

## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*
# Unit of Analysis + Time Window

One row represents one webpage for one day.

Table:
fact_content_daily_performance

Time Window:
2026-03

Prediction:
Rank webpages that should be refreshed.

Excluded:
Trend Direction because it creates the label.

In [44]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
con.sql(f"""
SELECT *
FROM read_parquet(
'{warehouse}/fact_content_daily_performance/**/*.parquet'
)
LIMIT 5
""").df()

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,gsc_data_available,ga4_data_available,gsc_impressions,gsc_clicks,gsc_sum_position,...,sessions_ai,ai_chatgpt,ai_perplexity,ai_gemini,ai_copilot,ai_claude,ai_meta,ai_other,scroll_events,month
0,2025-01-27,client_9958f0a7ae1df715,content_3b70a18ea133b2bb,True,True,True,False,30,0,115,...,0,0,0,0,0,0,0,0,0,2025-01
1,2025-01-27,client_9958f0a7ae1df715,content_fe8e8155ce1d47a2,True,True,True,False,5,0,358,...,0,0,0,0,0,0,0,0,0,2025-01
2,2025-01-27,client_9958f0a7ae1df715,content_b4462a1b90640058,True,True,True,False,1,0,34,...,0,0,0,0,0,0,0,0,0,2025-01
3,2025-01-27,client_9958f0a7ae1df715,content_c899aef92518c714,True,True,True,False,6,0,140,...,0,0,0,0,0,0,0,0,0,2025-01
4,2025-01-27,client_9958f0a7ae1df715,content_c7c1d2e68d9d0964,True,True,True,False,5,0,89,...,0,0,0,0,0,0,0,0,0,2025-01

## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*
## Features

Clicks

Impressions

CTR

Average Position

Content Age

## Label

Refresh Opportunity

## Context

Date

Month

Page

## Excluded

Trend Direction

Reason:

Trend Direction is used to build the label.
Using it causes data leakage.

In [46]:
con.sql(f"""
SELECT
  gsc_clicks AS clicks,
  gsc_impressions AS impressions,
  CASE WHEN gsc_impressions > 0 THEN (gsc_clicks * 100.0 / gsc_impressions) ELSE 0 END AS ctr,
  gsc_avg_position AS average_position
FROM read_parquet(
  '{warehouse}/fact_content_daily_performance/**/*.parquet'
)
LIMIT 10
""").df()

   clicks  impressions  ctr  average_position
0       0           30  0.0          3.833333
1       0            5  0.0         71.600000
2       0            1  0.0         34.000000
3       0            6  0.0         23.333333
4       0            5  0.0         17.800000
5       0           21  0.0         50.000000
6       0           13  0.0          9.769231
7       0           29  0.0         12.275862
8       0            5  0.0         20.600000
9       0            8  0.0         38.000000

In [48]:
con.sql(f"""
SELECT
  gsc_clicks AS clicks,
  gsc_impressions AS impressions,
  CASE WHEN gsc_impressions > 0 THEN (gsc_clicks * 100.0 / gsc_impressions) ELSE 0 END AS ctr,
  gsc_avg_position AS average_position
FROM read_parquet(
  '{warehouse}/fact_content_daily_performance/**/*.parquet'
)
LIMIT 10
""").df()

   clicks  impressions  ctr  average_position
0       0           30  0.0          3.833333
1       0            5  0.0         71.600000
2       0            1  0.0         34.000000
3       0            6  0.0         23.333333
4       0            5  0.0         17.800000
5       0           21  0.0         50.000000
6       0           13  0.0          9.769231
7       0           29  0.0         12.275862
8       0            5  0.0         20.600000
9       0            8  0.0         38.000000

In [49]:
con.sql(f"""
SELECT *

FROM read_parquet(
'{warehouse}/fact_content_daily_performance/**/*.parquet'
)

LIMIT 5
""").df()

ERROR:root:Unexpected exception finding object shape
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/google/colab/_debugpy_repr.py", line 54, in get_shape
    shape = getattr(obj, 'shape', None)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
duckdb.duckdb.HTTPException: HTTP Error: HTTP GET error on 'https://huggingface.co/api/datasets/FlyRank/internship-warehouse/tree/main/fact_content_daily_performance' (HTTP 401)

,report_date,client_hash_id,content_hash_id,client_has_gsc,client_has_ga4,...,ai_claude,ai_meta,ai_other,scroll_events,month
0,2025-01-27,client_9958f0a7ae1df715,content_3b70a18ea133b2bb,True,True,...,0,0,0,0,2025-01
1,2025-01-27,client_9958f0a7ae1df715,content_fe8e8155ce1d47a2,True,True,...,0,0,0,0,2025-01
2,2025-01-27,client_9958f0a7ae1df715,content_b4462a1b90640058,True,True,...,0,0,0,0,2025-01
3,2025-01-27,client_9958f0a7ae1df715,content_c899aef92518c714,True,True,...,0,0,0,0,2025-01
4,2025-01-27,client_9958f0a7ae1df715,content_c7c1d2e68d9d0964,True,True,...,0,0,0,0,2025-01

In [50]:
con.sql(f"""
SELECT

COUNT(*) AS total_rows

FROM read_parquet(
'{warehouse}/fact_content_daily_performance/**/*.parquet'
)

WHERE month='2026-03'
""").df()

   total_rows
0     9841378

In [52]:
con.sql(f"""
SELECT
  MIN(report_date) AS min_date,
  MAX(report_date) AS max_date
FROM read_parquet(
  '{warehouse}/fact_content_daily_performance/**/*.parquet'
)
WHERE month='2026-03'
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

    min_date   max_date
0 2026-03-01 2026-03-31

In [54]:
con.sql(f"""
SELECT
  COUNT(*)
FROM read_parquet(
  '{warehouse}/fact_content_daily_performance/**/*.parquet'
)
WHERE gsc_data_available IS TRUE
  AND month='2026-03'
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   count_star()
0       3611061

In [56]:
features = con.sql(f"""
SELECT
  gsc_clicks AS clicks,
  gsc_impressions AS impressions,
  CASE WHEN gsc_impressions > 0 THEN (gsc_clicks * 100.0 / gsc_impressions) ELSE 0 END AS ctr,
  gsc_avg_position AS average_position
FROM read_parquet(
  '{warehouse}/fact_content_daily_performance/**/*.parquet'
)
WHERE month='2026-03'
LIMIT 20
""").df()

features

    clicks  impressions       ctr  average_position
0        0           20  0.000000          3.350000
1        0            1  0.000000          0.000000
2        1          125  0.800000          4.928000
3        0            7  0.000000          4.000000
4        0           11  0.000000          2.272727
5        1          239  0.418410          7.347280
6        0          191  0.000000          7.832461
7        0           55  0.000000          3.272727
8        0           77  0.000000          5.636364
9        0            2  0.000000          4.500000
10       0            9  0.000000          7.444444
11       0            0  0.000000               NaN
12       0           14  0.000000          3.428571
13       0            2  0.000000          1.000000
14       0          223  0.000000          3.892377
15       0            6  0.000000          4.500000
16       0            1  0.000000          0.000000
17       0           12  0.000000          3.000000
18       2          126  1.587302          6.166667
19       0            5  0.000000         41.000000

Feature 1

Clicks

Knowable because previous clicks already exist.

Feature 2

Impressions

Already recorded before prediction.

Feature 3

CTR

Historical value.

Feature 4

Average Position

Already available.

Feature 5

Content Age

Known from publish date.

## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*
Trend Direction creates the label.

When it is added to the feature set,
model accuracy becomes unrealistically high.

Therefore,
Trend Direction must be removed before training.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*
Historical data cannot prove refresh causes ranking improvement.

This notebook is decision support only.

Only March 2026 was analyzed.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## Self-check

Before you submit, confirm each line honestly:

✔ Contract Completed

✔ Three Queries Executed

✔ Five Features Created

✔ Leakage Explained

✔ Data Limit Mentioned

✔ Runtime → Run All

✔ Saved to GitHub