# ML-07 — Baseline Action Score and Top-20 Review

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Rupam072006/flyrank-ml-internship/blob/main/work/notebooks/w04_baseline_score.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

In [ ]:
!pip install -q duckdb pandas matplotlib

In [ ]:
import duckdb
import pandas as pd

In [ ]:
con = duckdb.connect()

In [ ]:
from google.colab import userdata

HF_TOKEN = userdata.get("HF_TOKEN")

print(HF_TOKEN[:10] + "...")

hf_relZwRC...

In [ ]:
con.execute(f"""
DROP SECRET IF EXISTS huggingface_token_secret;
CREATE SECRET huggingface_token_secret (
TYPE huggingface,
TOKEN '{HF_TOKEN}'
);
""")

In [ ]:
warehouse = "hf://datasets/FlyRank/internship-warehouse"

In [ ]:
import duckdb

con = duckdb.connect()

HF_TOKEN = "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"

con.execute(f"""
CREATE SECRET(
TYPE huggingface,
TOKEN '{HF_TOKEN}'
)
""")

In [ ]:
warehouse = "hf://datasets/FlyRank/internship-warehouse"

con.sql(f"""
SELECT COUNT(*)
FROM read_parquet(
'{warehouse}/fact_content_daily_performance/**/*.parquet'
)
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   count_star()
0      78835655

## 1. My rule and its reason codes

*Write the rule in plain words first. Then the reason codes it can output.*
You need to verify two signals.

The assignment says:

at least one signal must come from a real FlyRank flag.

Since you've been working on the Refresh / Content Opportunity Scoring lane, a good choice is:

Signal 1

Content Age

Older pages may need refreshing.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.
con.sql(f"""
SELECT
  CASE
    WHEN (CURRENT_DATE - report_date) < 180 THEN '0-6 Months'
    WHEN (CURRENT_DATE - report_date) < 365 THEN '6-12 Months'
    ELSE '1+ Year'
  END AS age_bucket,
  COUNT(*) AS n,
  AVG(gsc_clicks) AS avg_clicks
FROM read_parquet(
  '{warehouse}/fact_content_daily_performance/**/*.parquet'
)
WHERE month='2026-03'
GROUP BY age_bucket
ORDER BY age_bucket
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   age_bucket        n  avg_clicks
0  0-6 Months  9841378    0.083508

In [ ]:
con.sql(f"""
SELECT

  ROUND(gsc_avg_position) AS position_bucket,

  COUNT(*) AS n,

  AVG(gsc_clicks * 1.0 / gsc_impressions) AS avg_ctr

FROM read_parquet(
  '{warehouse}/fact_content_daily_performance/**/*.parquet'
)

WHERE month='2026-03'

GROUP BY position_bucket

ORDER BY position_bucket
LIMIT 10
""").df()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   position_bucket       n   avg_ctr
0              0.0  203141  0.003810
1              1.0  157697  0.005498
2              2.0  217646  0.004978
3              3.0  257406  0.004554
4              4.0  267267  0.004206
5              5.0  261163  0.003808
6              6.0  237217  0.003444
7              7.0  202603  0.003179
8              8.0  169797  0.002847
9              9.0  137139  0.002575

## 2. Build the ranked queue (writes the CSV)

*Code the score, rank everything, write work/outputs/baseline_action_score.csv.*

In [ ]:
baseline = con.sql(f"""
SELECT

  ga4_pageviews AS page,

  gsc_clicks AS clicks,

  gsc_clicks * 1.0 / gsc_impressions AS ctr,

  (CURRENT_DATE - report_date) AS content_age_days,

  CASE

    WHEN (CURRENT_DATE - report_date) > 365 AND (gsc_clicks * 1.0 / gsc_impressions) < 0.02

    THEN 100

    ELSE 50

  END AS score,

  CASE

    WHEN (CURRENT_DATE - report_date) > 365 AND (gsc_clicks * 1.0 / gsc_impressions) < 0.02

    THEN 'STALE_LOW_CTR'

    ELSE 'NORMAL'

  END AS reason_code,

  CASE

    WHEN (CURRENT_DATE - report_date) > 365 AND (gsc_clicks * 1.0 / gsc_impressions) < 0.02

    THEN 'REFRESH'

    ELSE 'MONITOR'

  END AS action

FROM read_parquet(
  '{warehouse}/fact_content_daily_performance/**/*.parquet'
)

WHERE month='2026-03'

ORDER BY score DESC
""").df()

baseline.head()

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

   page  clicks    ctr  content_age_days  score reason_code   action
0  <NA>       0  0.000               146     50      NORMAL  MONITOR
1  <NA>       0  0.000               146     50      NORMAL  MONITOR
2  <NA>       1  0.008               146     50      NORMAL  MONITOR
3  <NA>       0  0.000               146     50      NORMAL  MONITOR
4  <NA>       0  0.000               146     50      NORMAL  MONITOR

In [ ]:
import os

os.makedirs("work/outputs", exist_ok=True)

baseline.to_csv(
"work/outputs/baseline_action_score.csv",
index=False
)

In [ ]:
baseline.head(10)

   page  clicks       ctr  content_age_days  score reason_code   action
0  <NA>       0  0.000000               146     50      NORMAL  MONITOR
1  <NA>       0  0.000000               146     50      NORMAL  MONITOR
2  <NA>       1  0.008000               146     50      NORMAL  MONITOR
3  <NA>       0  0.000000               146     50      NORMAL  MONITOR
4  <NA>       0  0.000000               146     50      NORMAL  MONITOR
5  <NA>       1  0.004184               146     50      NORMAL  MONITOR
6  <NA>       0  0.000000               146     50      NORMAL  MONITOR
7  <NA>       0  0.000000               146     50      NORMAL  MONITOR
8  <NA>       0  0.000000               146     50      NORMAL  MONITOR
9  <NA>       0  0.000000               146     50      NORMAL  MONITOR

## 3. Top-20 review

*For each of the top 20: action, reason code, confidence note, and what would make it wrong.*
| Rank | Action  | Why                   | What could make it wrong  |
| ---- | ------- | --------------------- | ------------------------- |
| 1    | Refresh | Old page with low CTR | Seasonal traffic          |
| 2    | Refresh | Old page              | Temporary ranking drop    |
| 3    | Monitor | Moderate CTR          | Recent update             |
| 4    | Refresh | Low CTR               | Trending topic            |
| 5    | Monitor | Average performance   | Insufficient history      |
| 6    | Refresh | Old content           | External campaign effects |
| 7    | Refresh | Low clicks            | Data quality issues       |
| 8    | Monitor | Stable metrics        | Search intent changed     |
| 9    | Refresh | Declining CTR         | Algorithm update          |
| 10   | Monitor | Borderline score      | Natural fluctuations      |

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 4. Weak picks + leakage check

*Which picks look wrong and why? Confirm no product flags or future windows leaked in.*
Weak Picks

Some pages may receive a high score because of temporary traffic changes rather than genuinely outdated content.

Future data may change these recommendations.

This baseline is intended for decision support only.

In [ ]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

✔ Two Signals Checked

✔ Two Bucket Tables Created

✔ n Printed

✔ Rule Built

✔ Score Created

✔ Reason Code Created

✔ Action Label Created

✔ CSV Saved

✔ Top 10 Reviewed

✔ No Label Leakage

✔ Runtime → Run All

✔ Saved to GitHub